apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: engine-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: engine-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 1
  desiredReplicas: 0