apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-servicemonitor
  labels:
    app: user-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: user-service
  endpoints:
  - port: metrics
    interval: 15s
    scheme: http