{
 "title": "Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Websockets", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Current WebSockets",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(websocket_connections{})" }
   ]
  },
  {
   "title": "WebSocket Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 1 },
   "targets": [
    { "expr": "websocket_connections{}", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Inbound WS Messages / Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(websocket_inbound_messages{}[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Outbound WS Messages / Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "rate(websocket_outbound_messages{}[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Engine", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Engine CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container=\"engine-service\"}[80s]))[30m:5s]",
     "legendFormat": "engine_actual_cpu_usage"
    },
    { "target": "engine_prediction" }
   ]
  },
  {
   "title": "Avg. Search Time for most difficult positions",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "target": "engine_difficult_positions" }
   ]
  },
  { "title": "User Service", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "URI Request",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(uri, instance) (gin_uri_request_total)",
     "legendFormat": "{{instance}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(gin_request_duration_bucket[5m])) by (le, pod))",
     "legendFormat": "{{pod}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(gin_request_duration_bucket[5m])) by (le, pod))",
     "legendFormat": "{{pod}}-p99"
    },
    {
     "expr": "sum (gin_request_duration_sum) / sum(gin_request_duration_count)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Traffic In-Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gin_request_body_total[5m])",
     "legendFormat": "{{pod}}-in"
    },
    {
     "expr": "rate(gin_response_body_total[5m])",
     "legendFormat": "{{pod}}-out"
    }
   ]
  }
 ]
}